name: testing

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run npm install, lint, test, and build
      run: |
        npm ci
        npm run lint
        npm run test
        npm run build
      env:
        CI: true
